# Generated by Django 4.1.3 on 2023-01-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Repuesto', models.CharField(max_length=100)),
                ('Vehiculo', models.CharField(max_length=100)),
                ('Detalle', models.TextField(max_length=3000)),
                ('Precio', models.CharField(max_length=10)),
            ],
        ),
    ]
