# Generated by Django 4.1.3 on 2023-01-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo_dos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='texto',
            new_name='Detalle',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sub_titulo',
            new_name='Repuesto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='Vehiculo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publicado_el',
        ),
    ]
